### ISSUE TITLE
Maintainer of Official image

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Deploy.to.Cloud#20]
https://github.com/RocketChat/Deploy.to.Cloud/blob/master/OfficialImage/Dockerfile#L3

It can be me, but I didn't want to enter the project like this!

**Comment by pierreozoux** [comment]
And if you want, I can submit it, and follow the process (I'm really interested to learn this.)

**Comment by Sing-Li** [comment]
@pierreozoux   -  Actually, I think it will be best to have a separate repository just for this dockerfile (and the doc).      I saw some review comment about another project moving the git repos too many times :)  I was going to change the maintainer then.

The thing is... every time we have a new tagged build - we will need to submit it again (although the review will be shorter).

Yes - please submit it through the process.  (we will need an associated docs created and submitted too - please add it to this repos).

**Comment by Sing-Li** [comment]
@engelgabriel   is fast!!    :+1:    Thanks Gariel.

@pierreozoux  please place official image and docs (and submit from) this new repos:

https://github.com/RocketChat/Docker.Official.Image

**Comment by pierreozoux** [comment]
@engelgabriel I can't even fork this repo :)

**Comment by Sing-Li** [comment]
@pierreozoux  - are you doing it from the button on github UI ?  We changed the repo name - to reflect how it evolved.

**Comment by Sing-Li** [comment]
@pierreozoux   -  fork-able now :)

**Comment by pierreozoux** [comment]
Ok, done

https://github.com/RocketChat/Docker.Official.Image

I wait your final review to start PR the official repo!

Cheers!

**Comment by Sing-Li** [comment]
@engelgabriel  - please take a look at the readme 'blurb' and make sure it is ok.  That will be the 'official blurb' when approved.     

(@pierreozoux -  I will try everything later tonight and post results back here.  Please hold until then. Thanks!)

**Comment by engelgabriel** [comment]
NICE! WELDONE GUYS!

konecty*Gabriel Engel*Co-founder and CEOskype: gabriel_engel

gabriel.engel@konecty.com

+55 51 98089422 <+555198089422>

+55 51 30855151 <+555130855151>

www.konecty.com

**Comment by pierreozoux** [comment]
I think this can be closed now :)
