### ISSUE TITLE
Digital Ocean support?

### ISSUE THREAD

**Issue by katopz** [RocketChat/Deploy.to.Cloud#21]
I didn't see Digital Ocean folder which mean no support for it am I right?
PS : I do try this via Digital Ocean with pre install Docker

```shell
root@foo:~# docker pull rocketchat/rocket.chat
```
and got
```shell
Using default tag: latest
Post http:///var/run/docker.sock/v1.20/images/create?fromImage=rocketchat%2Frocket.chat%3Alatest: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

Any hint?

**Comment by pierreozoux** [comment]
Hi!

It is not yet an official image, hopefully by the end of the week it wlll be :)

**Comment by katopz** [comment]
@pierreozoux Cool! I'm pretty new to Docker (just say hello to it 5 min. ago) so I think I better wait :grin:

**Comment by pierreozoux** [comment]
I'll let you know once done :) And I'd be happy to help!

**Comment by eclickhu** [comment]
Any update on DC deploy? Thanks!

**Comment by pierreozoux** [comment]
Oops sorry, I forgot to update here.

@eclickhu start a docker application on DO, and then follow these instructions: https://github.com/RocketChat/Deploy.to.Cloud/tree/master/GenericLinux

And you should be fine.

If there is anything, please let me know!

I close this for now.

**Comment by Sing-Li** [comment]
@eclickhu Please revisit "the empty page" for detailed deployment instructions - with or without Docker support.   Thx.
